# Generated by Django 2.1.1 on 2018-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='categoria',
        ),
        migrations.AddField(
            model_name='articles',
            name='categoria',
            field=models.CharField(choices=[('Asterisk', 'Asterisk'), ('Python', 'Python'), ('Docker', 'Docker'), ('GCD', 'Google Cloud'), ('AWS', 'AWS'), ('Cursos', 'Cursos'), ('Tutorial', 'Tutorial'), ('Linux', 'Linux'), ('Hackers', 'Hackers'), ('Django', 'Django'), ('All', 'All')], default='Tutorial', max_length=20),
        ),
    ]
